# GENERATED by references/build_reference_image.sh --standard-chrom-only false
# (representative: zebrafish/danRer11).
# SEQSTYLE-FIX reference recipe: TxDb2GRangesList(txdb, standardChromOnly = FALSE).
# Used by organisms whose species has NO GenomeInfoDb UCSC seqlevels-style entry,
# so keepStandardChromosomes(species=...) would abort in extractSeqlevels():
#   zebrafish (Danio rerio), chicken (Gallus gallus).
# Trade-off: keeps ALL contigs the source TxDb annotates (no standard-chrom pruning).
# Per-organism values are injected as ARG defaults; each built image also embeds
# its exact Dockerfile at /image-refs/<organism>/Dockerfile. Do not hand-edit.
#
# ---- Stage 1: builder (full R/Bioconductor) — produces /image-refs/<organism> ----
FROM bioconductor/bioconductor_docker:3.19 AS builder

ARG ORGANISM=ORGANISM
ARG ORGANISM_LABEL="LABEL"
ARG GENOME_BUILD="BUILD"
ARG GENOME_PACKAGE="GENOME_PKG"
ARG ANNOTATION_PACKAGE="ANNOT_PKG"
ARG ANNOTATION_OBJECT="ANNOT_OBJ"
ARG ANNOTATION_LOADER="rds"
ARG ANNOTATION_SOURCE_LOADER="package-object"
ARG ANNOTATION_TRANSFORM="txdb2grangeslist"
ARG ANNOTATION_RDS_PATH="annotation/txdb.rds"

ENV ORGANISM=${ORGANISM}
ENV ORGANISM_LABEL=${ORGANISM_LABEL}
ENV GENOME_BUILD=${GENOME_BUILD}
ENV GENOME_PACKAGE=${GENOME_PACKAGE}
ENV ANNOTATION_PACKAGE=${ANNOTATION_PACKAGE}
ENV ANNOTATION_OBJECT=${ANNOTATION_OBJECT}
ENV ANNOTATION_LOADER=${ANNOTATION_LOADER}
ENV ANNOTATION_SOURCE_LOADER=${ANNOTATION_SOURCE_LOADER}
ENV ANNOTATION_TRANSFORM=${ANNOTATION_TRANSFORM}
ENV ANNOTATION_RDS_PATH=${ANNOTATION_RDS_PATH}
ENV PREDITR_REFERENCE_DIR=/image-refs/${ORGANISM}
ENV PREDITR_REFERENCE_RLIB=/image-refs/${ORGANISM}/rlib

RUN mkdir -p "${PREDITR_REFERENCE_RLIB}" "${PREDITR_REFERENCE_DIR}" "${PREDITR_REFERENCE_DIR}/annotation"

RUN Rscript -e 'options(repos = c(CRAN = "https://cloud.r-project.org")); if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager"); BiocManager::install(version = "3.19", ask = FALSE, update = FALSE)'

RUN Rscript -e 'options(repos = c(CRAN = "https://cloud.r-project.org")); cran_packages <- c("jsonlite"); if (length(cran_packages) > 0) install.packages(cran_packages, lib = Sys.getenv("PREDITR_REFERENCE_RLIB"))'

RUN Rscript -e 'options(repos = c(CRAN = "https://cloud.r-project.org")); .libPaths(c(Sys.getenv("PREDITR_REFERENCE_RLIB"), .libPaths())); packages <- c("GENOME_PKG"); BiocManager::install(packages, lib = Sys.getenv("PREDITR_REFERENCE_RLIB"), ask = FALSE, update = FALSE)'

# Build-only Bioconductor packages (e.g. crisprDesign and the source TxDb) are
# needed only to produce annotation/txdb.rds. They install into the default
# library, NOT the shipped rlib, so they do not bloat the reference payload.
RUN Rscript -e 'options(repos = c(CRAN = "https://cloud.r-project.org")); build_only <- c("crisprDesign", "ANNOT_PKG"); if (length(build_only) > 0) BiocManager::install(build_only, ask = FALSE, update = FALSE)'

# GitHub packages (e.g. crisprDesignData) are only needed at build time to
# produce annotation/txdb.rds, so they install into the default library rather
# than the shipped rlib.
RUN Rscript -e 'options(repos = c(CRAN = "https://cloud.r-project.org")); gh <- c(); if (length(gh) > 0) { if (!requireNamespace("remotes", quietly = TRUE)) install.packages("remotes"); remotes::install_github(gh, upgrade = "never") }'

RUN Rscript -e '.libPaths(c(Sys.getenv("PREDITR_REFERENCE_RLIB"), .libPaths())); if (identical(Sys.getenv("ANNOTATION_LOADER"), "rds")) { load_source <- function() { if (identical(Sys.getenv("ANNOTATION_SOURCE_LOADER"), "data")) { env <- new.env(parent = emptyenv()); utils::data(list = Sys.getenv("ANNOTATION_OBJECT"), package = Sys.getenv("ANNOTATION_PACKAGE"), envir = env); env[[Sys.getenv("ANNOTATION_OBJECT")]] } else { getExportedValue(Sys.getenv("ANNOTATION_PACKAGE"), Sys.getenv("ANNOTATION_OBJECT")) } }; txdb <- load_source(); if (identical(Sys.getenv("ANNOTATION_TRANSFORM"), "txdb2grangeslist")) { txdb <- crisprDesign::TxDb2GRangesList(txdb, standardChromOnly = FALSE) }; rds_path <- file.path(Sys.getenv("PREDITR_REFERENCE_DIR"), Sys.getenv("ANNOTATION_RDS_PATH")); dir.create(dirname(rds_path), recursive = TRUE, showWarnings = FALSE); saveRDS(txdb, rds_path) }'

RUN Rscript -e 'ref_dir <- Sys.getenv("PREDITR_REFERENCE_DIR"); manifest <- file.path(ref_dir, "preditr_reference.json"); packages <- c("GENOME_PKG"); annotation_path_line <- if (identical(Sys.getenv("ANNOTATION_LOADER"), "rds")) paste0("  \"annotation_path\": \"", Sys.getenv("ANNOTATION_RDS_PATH"), "\"", ",") else NULL; lines <- c("{", "  \"schema_version\": \"0.1\",", paste0("  \"organism_id\": \"", Sys.getenv("ORGANISM"), "\"", ","), paste0("  \"organism_label\": \"", Sys.getenv("ORGANISM_LABEL"), "\"", ","), paste0("  \"genome_build\": \"", Sys.getenv("GENOME_BUILD"), "\"", ","), "  \"reference_kind\": \"bioconductor_packages\",", "  \"bioconductor_version\": \"3.19\",", "  \"r_library_path\": \"rlib\",", paste0("  \"genome_package\": \"", Sys.getenv("GENOME_PACKAGE"), "\"", ","), paste0("  \"annotation_package\": \"", Sys.getenv("ANNOTATION_PACKAGE"), "\"", ","), paste0("  \"annotation_object\": \"", Sys.getenv("ANNOTATION_OBJECT"), "\"", ","), paste0("  \"annotation_loader\": \"", Sys.getenv("ANNOTATION_LOADER"), "\"", ","), paste0("  \"annotation_source_loader\": \"", Sys.getenv("ANNOTATION_SOURCE_LOADER"), "\"", ","), paste0("  \"annotation_transform\": \"", Sys.getenv("ANNOTATION_TRANSFORM"), "\"", ","), annotation_path_line, "  \"packages\": [", paste0("    ", paste(sprintf("\"%s\"", packages), collapse = ",\n    ")), "  ]", "}"); writeLines(lines, manifest)'

RUN Rscript -e '.libPaths(c(Sys.getenv("PREDITR_REFERENCE_RLIB"), .libPaths())); pkgs <- installed.packages(lib.loc = Sys.getenv("PREDITR_REFERENCE_RLIB")); utils::write.table(as.data.frame(pkgs[, c("Package", "Version", "LibPath")]), file = file.path(Sys.getenv("PREDITR_REFERENCE_DIR"), "installed_packages.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)'

RUN Rscript -e 'loader <- c("load_preditr_reference_payload <- function(reference_dir) {", "  manifest <- jsonlite::fromJSON(file.path(reference_dir, \"preditr_reference.json\"))", "  .libPaths(c(file.path(reference_dir, manifest$r_library_path), .libPaths()))", "  requireNamespace(manifest$genome_package, quietly = FALSE)", "  requireNamespace(manifest$annotation_package, quietly = FALSE)", "  if (identical(manifest$annotation_loader, \"data\")) {", "    env <- new.env(parent = emptyenv())", "    utils::data(list = manifest$annotation_object, package = manifest$annotation_package, envir = env)", "    txdb <- env[[manifest$annotation_object]]", "  } else if (identical(manifest$annotation_loader, \"package-object\")) {", "    txdb <- getExportedValue(manifest$annotation_package, manifest$annotation_object)", "  } else if (identical(manifest$annotation_loader, \"rds\")) {", "    txdb <- readRDS(file.path(reference_dir, manifest$annotation_path))", "  } else {", "    stop(\"Unsupported annotation_loader: \", manifest$annotation_loader)", "  }", "  list(manifest = manifest, txdb = txdb, genome_package = manifest$genome_package)", "}"); writeLines(loader, file.path(Sys.getenv("PREDITR_REFERENCE_DIR"), "reference_loader.R"))'

# Embed the exact Dockerfile used to build this reference into the payload, so each
# image self-documents how it was produced (organisms needing the seqstyle workaround
# ship a different Dockerfile than the standard ones).
COPY reference.Dockerfile /image-refs/ORGANISM/Dockerfile

ENV PREDITR_ALLOW_NON_BUILTIN_REFERENCE=TRUE
ENV PREDITR_ALLOW_MISSING_MAPS=TRUE
COPY check_reference_compatibility.R /tmp/check_reference_compatibility.R
COPY maps /tmp/preditr-maps

RUN if [ -d "/tmp/preditr-maps/${ORGANISM}" ]; then cp -a "/tmp/preditr-maps/${ORGANISM}" "${PREDITR_REFERENCE_DIR}/maps"; fi

RUN Rscript /tmp/check_reference_compatibility.R "${PREDITR_REFERENCE_DIR}" /tmp/preditr-maps

# Strip help/docs/vignettes/tests from the shipped rlib — not needed at runtime.
# Keeps DESCRIPTION/NAMESPACE/R/libs/data/extdata (the 2bit genome is in extdata).
RUN find "${PREDITR_REFERENCE_RLIB}" -type d \( -name help -o -name html -o -name doc -o -name examples -o -name tests -o -name unitTests \) -exec rm -rf {} + 2>/dev/null || true

# ---- Stage 2: minimal carrier (no R) — only the payload + a shell to copy it ----
FROM debian:stable-slim
COPY --from=builder /image-refs/ORGANISM /image-refs/ORGANISM
CMD ["sh", "-c", "rm -rf /refs/ORGANISM && mkdir -p /refs && cp -a /image-refs/ORGANISM /refs/ORGANISM"]

